CREATE DATABASE IF NOT EXISTS NYC_TAXI;

CREATE SCHEMA IF NOT EXISTS NYC_TAXI.RAW;

CREATE WAREHOUSE IF NOT EXISTS NYC_TAXI_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE DATABASE NYC_TAXI;
USE SCHEMA RAW;
USE WAREHOUSE NYC_TAXI_WH;

SELECT CURRENT_DATABASE();
SELECT CURRENT_SCHEMA();
SELECT CURRENT_WAREHOUSE();

SHOW STAGES IN SCHEMA NYC_TAXI.RAW;