LIST @NYC_TAXI.RAW.TLC_STAGE;

SHOW FILE FORMATS IN SCHEMA NYC_TAXI.RAW;

CREATE FILE FORMAT NYC_TAXI.RAW.PARQUET_FORMAT
    TYPE = PARQUET;


CREATE TABLE NYC_TAXI.RAW.YELLOW_TAXI
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(
        INFER_SCHEMA(
            LOCATION => '@NYC_TAXI.RAW.TLC_STAGE',
            FILE_FORMAT => 'NYC_TAXI.RAW.PARQUET_FORMAT'
        )
    )
);

DESC TABLE NYC_TAXI.RAW.YELLOW_TAXI;

COPY INTO NYC_TAXI.RAW.YELLOW_TAXI
FROM @NYC_TAXI.RAW.TLC_STAGE
FILE_FORMAT = (
    FORMAT_NAME = 'NYC_TAXI.RAW.PARQUET_FORMAT'
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;


SELECT *
FROM NYC_TAXI.RAW.YELLOW_TAXI
LIMIT 10;

USE DATABASE NYC_TAXI;
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'RAW'
  AND TABLE_NAME = 'YELLOW_TAXI'
ORDER BY ORDINAL_POSITION;